import { CANONICAL_HOST, OPEN_GRAPH_TITLE, SITE_DISPLAY_NAME } from "@/lib/site-url"

const DEFAULT_TITLE = OPEN_GRAPH_TITLE

function dedupeKeywords(words: string[]): string[] {
  const seen = new Set<string>()
  return words.filter((w) => {
    const key = w.trim().toLowerCase()
    if (!key || seen.has(key)) return false
    seen.add(key)
    return true
  })
}

/** Comprehensive WEX Health keywords from user requirements */
export const USER_SUPPLIED_KEYWORDS = [
  // Primary login keywords
  "WEX Health login",
  "WEX Health benefits login",
  "WEX Health login page",
  "WEX benefits login",
  "WEX benefits account login",
  "WEX employee benefits login",
  "WEX participant login",
  "WEX participant portal",
  "WEX benefits participant login",
  "WEX benefits portal",
  "WEX Health benefits",
  "WEX employee benefits",
  "WEX health benefits",
  "WEX account login",
  "WEX Health account login",

  // HSA keywords
  "WEX HSA",
  "WEX HSA login",
  "WEX HSA account",
  "WEX HSA account login",
  "WEX Health HSA",
  "WEX Health HSA login",
  "WEX HSA participant login",
  "WEX HSA portal",
  "WEX Health Savings Account",
  "WEX Health Savings Account login",
  "WEX HSA benefits",
  "WEX HSA balance",
  "WEX HSA claims",
  "WEX HSA reimbursement",
  "WEX HSA card",
  "WEX HSA debit card",

  // FSA keywords
  "WEX FSA",
  "WEX FSA login",
  "WEX FSA account",
  "WEX FSA account login",
  "WEX Health FSA",
  "WEX Health FSA login",
  "WEX Flexible Spending Account",
  "WEX Flexible Spending Account login",
  "WEX FSA participant login",
  "WEX FSA portal",
  "WEX FSA reimbursement",
  "WEX FSA claims",
  "WEX FSA balance",
  "WEX FSA card",

  // HRA keywords
  "WEX HRA",
  "WEX HRA login",
  "WEX HRA account",
  "WEX HRA account login",
  "WEX Health HRA",
  "WEX Health HRA login",
  "WEX Health Reimbursement Account",
  "WEX Health Reimbursement Account login",
  "WEX HRA participant login",
  "WEX HRA portal",
  "WEX HRA reimbursement",

  // LSA keywords
  "WEX LSA",
  "WEX LSA login",
  "WEX Lifestyle Spending Account",
  "WEX Lifestyle Spending Account login",
  "WEX commuter benefits",
  "WEX commuter benefits login",
  "WEX commuter account",
  "WEX reimbursement account",
  "WEX benefits card",
  "WEX benefits debit card",

  // General benefits keywords
  "WEX employee benefits account",
  "WEX employee benefits portal",
  "WEX employee health benefits",
  "WEX health account",
  "WEX health account login",
  "WEX spending account",
  "WEX spending account login",
  "WEX reimbursement account login",
  "WEX benefits account",
  "WEX benefits account balance",
  "WEX benefits claims",
  "WEX benefits reimbursement",
  "WEX benefits enrollment",
  "WEX benefits open enrollment",
  "WEX benefit elections",

  // Participant portal keywords
  "WEX Health participant portal",
  "WEX Health participant login",
  "WEX Health participant account",
  "WEX Health employee portal",
  "WEX Health employee login",
  "WEX Health benefits portal",
  "WEX Health account",
  "WEX Health account login",
  "WEX Health participant account login",

  // Special programs
  "WEX COBRA login",
  "WEX retiree benefits login",
  "WEX leave of absence benefits login",
] as const

/**
 * Keywords derived from LOGIN_REDIRECT_URL metadata + portal copy
 * https://benefitslogin.wexhealth.com/Login.aspx?ReturnUrl=%2f
 */
export const DESTINATION_KEYWORDS = [
  "benefitslogin.wexhealth.com",
  "benefitslogin.wexhealth.com login",
  "Login.aspx",
  "Login.aspx?ReturnUrl=%2f",
  "Login - WEX Health Inc",
  "WEX Health Inc",
  "WEX Health Inc login",
  "Login WEX Health Inc",
  "Existing User",
  "Existing User login",
  "Existing Users",
  "New Users",
  "New User",
  "Get Started",
  "Remember Me",
  "Username",
  "Username required",
  "Next",
  "Skip to content",
  "Wex Health member website login",
  "Wex Health benefitslogin",
  "benefitslogin wex health",
  "benefitslogin.wexhealth.com Username",
  "benefitslogin.wexhealth.com Existing User",
  "benefitslogin.wexhealth.com Remember Me",
  "benefitslogin.wexhealth.com Get Started",
  "Powered by WEX Health",
  "Participant Services",
  "Participant Services WEX",
  "Call Participant Services",
  "866-451-3399",
  "(866) 451-3399",
  "loginassistance.wexhealth",
  "benefitslogin.wexhealth.com loginassistance",
  "WEX Benefits",
  "WEX Benefits login",
  "Generic Login WEX Benefits",
  "mybenefits.wexhealth.com",
  "mybenefits.wexhealth.com login",
  "benefitexpress",
  "benefitexpress login",
  "benefitexpress Business Party",
  "benefitexpress WEX Health",
  "benefit account",
  "benefit account login",
  "benefit account(s)",
  "file a claim",
  "view account balance",
  "account balance and summary",
  "direct deposit benefits",
  "FREE direct deposit",
  "email notifications benefits",
  "single source benefit account",
  "WEX Health benefit accounts",
  "Wex Health Existing User login",
  "Wex Health New Users Get Started",
  "sign in to WEX Health Inc",
  "log in to benefitslogin.wexhealth.com",
  "access WEX Health benefits account",
  "WEX Health Inc participant portal",
  "WEX Health Inc HSA FSA login",
] as const

/**
 * SEO keywords — Wex Health / HSA FSA / final portal URL intents.
 * Final egress: https://benefitslogin.wexhealth.com/Login.aspx?ReturnUrl=%2f
 */
export const SITE_SEO_KEYWORDS = dedupeKeywords([
  "Wex Health",
  "WEX Health",
  "WEX",
  SITE_DISPLAY_NAME,
  CANONICAL_HOST,
  "wexhealthbenefitsaccount.com",
  "wexhealthbenefitsaccount.com login",
  "health benefits",
  "HSA login",
  "FSA login",
  "health savings account",
  "flexible spending account",
  "employee benefits",
  DEFAULT_TITLE,
  "Wex Health login",
  "WEX Health login",
  "Wex Health HSA",
  "Wex Health FSA",
  "Wex Health HSA login",
  "Wex Health FSA login",
  "benefitslogin.wexhealth.com",
  "benefitslogin.wexhealth.com login",
  "benefitslogin.wexhealth.com Login.aspx",
  "Login.aspx Wex Health",
  "Wex Health Login.aspx",
  "WEX HSA login",
  "WEX FSA login",
  "WEX COBRA login",
  "HRA login",
  "health reimbursement arrangement",
  "commuter benefits Wex Health",
  "dependent care FSA WEX",
  "employee health benefits login",
  "employer health benefits portal",
  "benefits account login",
  "health benefits member portal",
  "Wex Health employee benefits",
  "WEX employee benefits login",
  "Wex Health benefits portal",
  "sign in",
  "log on",
  "forgot password",
  "reset password",
  "verify identity",
  "access code",
  "health benefits sign in",
  "Wex Health portal",
  "Wex Health open enrollment",
  "employee benefits portal",
  "employee benefits login",
  "open enrollment login",
  "health benefits login",
  ...USER_SUPPLIED_KEYWORDS,
  ...DESTINATION_KEYWORDS,
])

/** Alias used by CrawlerSeoPage / shared SEO body copy. */
export const SITE_KEYWORDS = SITE_SEO_KEYWORDS
