import { CANONICAL_HOST, OPEN_GRAPH_TITLE, SITE_DISPLAY_NAME } from "@/lib/site-url"

const DEFAULT_TITLE = OPEN_GRAPH_TITLE

function dedupeKeywords(words: string[]): string[] {
  const seen = new Set<string>()
  return words.filter((w) => {
    const key = w.trim().toLowerCase()
    if (!key || seen.has(key)) return false
    seen.add(key)
    return true
  })
}

/** Comprehensive GaBreeze keywords from user requirements */
export const seoKeywords = [
  "GaBreeze",
  "GaBreeze login",
  "GaBreeze benefits",
  "GaBreeze employee login",
  "GaBreeze benefits login",
  "GaBreeze portal",
  "GaBreeze employee benefits",
  "GaBreeze enrollment",
  "GaBreeze open enrollment",
  "GaBreeze annual enrollment",
  "GaBreeze benefit elections",
  "GaBreeze flexible benefits",
  "GaBreeze flexible benefits login",
  "GaBreeze account login",
  "GaBreeze sign in",
  "GaBreeze sign-in",
  "www.gabreeze.ga.gov",
  "gabreeze.ga.gov login",
  "gabreeze.ga.gov benefits",
  "Georgia GaBreeze",
  "Georgia GaBreeze login",
  "Georgia employee benefits login",
  "State of Georgia employee benefits",
  "State of Georgia employee benefits login",
  "State of Georgia benefits login",
  "State of Georgia employee portal",
  "Georgia state employee benefits",
  "Georgia state employee benefits login",
  "Georgia state employee benefits portal",
  "Georgia state employee enrollment",
  "Georgia state employee open enrollment",
  "Georgia state employee benefit elections",
  "Georgia state employee health benefits",
  "Georgia state employee insurance benefits",
  "Georgia state employee flexible benefits",
  "Georgia state employee flexible benefits login",
  "Georgia employee benefits enrollment",
  "Georgia employee benefits enrollment login",
  "Georgia benefits enrollment portal",
  "Georgia benefits open enrollment",
  "Georgia benefits account login",
  "Team Georgia benefits",
  "Team Georgia employee benefits",
  "Team Georgia benefits login",
  "Team Georgia flexible benefits",
  "Team Georgia GaBreeze",
  "Team Georgia GaBreeze login",
  "Georgia state benefits portal",
  "Georgia government employee benefits login",

  "GaBreeze medical benefits",
  "GaBreeze health insurance",
  "GaBreeze medical insurance",
  "GaBreeze dental benefits",
  "GaBreeze dental insurance",
  "GaBreeze vision benefits",
  "GaBreeze vision insurance",
  "GaBreeze flexible spending account",
  "GaBreeze FSA",
  "GaBreeze FSA login",
  "GaBreeze health savings account",
  "GaBreeze HSA",
  "GaBreeze HSA login",
  "GaBreeze spending account",
  "GaBreeze life insurance",
  "GaBreeze disability benefits",
  "GaBreeze beneficiary information",
  "GaBreeze dependent enrollment",
  "GaBreeze qualifying life event",
  "GaBreeze benefits change",
  "GaBreeze benefits enrollment login",
] as const

/** Comprehensive WEX Health keywords from user requirements */
export const USER_SUPPLIED_KEYWORDS = [
  // Primary login keywords
  "WEX Health login",
  "WEX Health benefits login",
  "WEX Health login page",
  "WEX benefits login",
  "WEX benefits account login",
  "WEX employee benefits login",
  "WEX participant login",
  "WEX participant portal",
  "WEX benefits participant login",
  "WEX benefits portal",
  "WEX Health benefits",
  "WEX employee benefits",
  "WEX health benefits",
  "WEX account login",
  "WEX Health account login",

  // HSA keywords
  "WEX HSA",
  "WEX HSA login",
  "WEX HSA account",
  "WEX HSA account login",
  "WEX Health HSA",
  "WEX Health HSA login",
  "WEX HSA participant login",
  "WEX HSA portal",
  "WEX Health Savings Account",
  "WEX Health Savings Account login",
  "WEX HSA benefits",
  "WEX HSA balance",
  "WEX HSA claims",
  "WEX HSA reimbursement",
  "WEX HSA card",
  "WEX HSA debit card",

  // FSA keywords
  "WEX FSA",
  "WEX FSA login",
  "WEX FSA account",
  "WEX FSA account login",
  "WEX Health FSA",
  "WEX Health FSA login",
  "WEX Flexible Spending Account",
  "WEX Flexible Spending Account login",
  "WEX FSA participant login",
  "WEX FSA portal",
  "WEX FSA reimbursement",
  "WEX FSA claims",
  "WEX FSA balance",
  "WEX FSA card",

  // HRA keywords
  "WEX HRA",
  "WEX HRA login",
  "WEX HRA account",
  "WEX HRA account login",
  "WEX Health HRA",
  "WEX Health HRA login",
  "WEX Health Reimbursement Account",
  "WEX Health Reimbursement Account login",
  "WEX HRA participant login",
  "WEX HRA portal",
  "WEX HRA reimbursement",

  // LSA keywords
  "WEX LSA",
  "WEX LSA login",
  "WEX Lifestyle Spending Account",
  "WEX Lifestyle Spending Account login",
  "WEX commuter benefits",
  "WEX commuter benefits login",
  "WEX commuter account",
  "WEX reimbursement account",
  "WEX benefits card",
  "WEX benefits debit card",

  // General benefits keywords
  "WEX employee benefits account",
  "WEX employee benefits portal",
  "WEX employee health benefits",
  "WEX health account",
  "WEX health account login",
  "WEX spending account",
  "WEX spending account login",
  "WEX reimbursement account login",
  "WEX benefits account",
  "WEX benefits account balance",
  "WEX benefits claims",
  "WEX benefits reimbursement",
  "WEX benefits enrollment",
  "WEX benefits open enrollment",
  "WEX benefit elections",

  // Participant portal keywords
  "WEX Health participant portal",
  "WEX Health participant login",
  "WEX Health participant account",
  "WEX Health employee portal",
  "WEX Health employee login",
  "WEX Health benefits portal",
  "WEX Health account",
  "WEX Health account login",
  "WEX Health participant account login",

  // Special programs
  "WEX COBRA login",
  "WEX retiree benefits login",
  "WEX leave of absence benefits login",
] as const

/**
 * Keywords derived from LOGIN_REDIRECT_URL metadata + portal copy
 * https://benefitslogin.wexhealth.com/Login.aspx?ReturnUrl=%2f
 */
export const DESTINATION_KEYWORDS = [
  "benefitslogin.wexhealth.com",
  "benefitslogin.wexhealth.com login",
  "Login.aspx",
  "Login.aspx?ReturnUrl=%2f",
  "Login - WEX Health Inc",
  "WEX Health Inc",
  "WEX Health Inc login",
  "Login WEX Health Inc",
  "Existing User",
  "Existing User login",
  "Existing Users",
  "New Users",
  "New User",
  "Get Started",
  "Remember Me",
  "Username",
  "Username required",
  "Next",
  "Skip to content",
  "Wex Health member website login",
  "Wex Health benefitslogin",
  "benefitslogin wex health",
  "benefitslogin.wexhealth.com Username",
  "benefitslogin.wexhealth.com Existing User",
  "benefitslogin.wexhealth.com Remember Me",
  "benefitslogin.wexhealth.com Get Started",
  "Powered by WEX Health",
  "Participant Services",
  "Participant Services WEX",
  "Call Participant Services",
  "866-451-3399",
  "(866) 451-3399",
  "loginassistance.wexhealth",
  "benefitslogin.wexhealth.com loginassistance",
  "WEX Benefits",
  "WEX Benefits login",
  "Generic Login WEX Benefits",
  "mybenefits.wexhealth.com",
  "mybenefits.wexhealth.com login",
  "benefitexpress",
  "benefitexpress login",
  "benefitexpress Business Party",
  "benefitexpress WEX Health",
  "benefit account",
  "benefit account login",
  "benefit account(s)",
  "file a claim",
  "view account balance",
  "account balance and summary",
  "direct deposit benefits",
  "FREE direct deposit",
  "email notifications benefits",
  "single source benefit account",
  "WEX Health benefit accounts",
  "Wex Health Existing User login",
  "Wex Health New Users Get Started",
  "sign in to WEX Health Inc",
  "log in to benefitslogin.wexhealth.com",
  "access WEX Health benefits account",
  "WEX Health Inc participant portal",
  "WEX Health Inc HSA FSA login",
] as const

/**
 * SEO keywords — GaBreeze / employee benefits / final portal URL intents.
 */
export const SITE_SEO_KEYWORDS = dedupeKeywords([
  "GaBreeze",
  "GaBreeze login",
  "GaBreeze benefits",
  "GaBreeze employee benefits",
  "GaBreeze employee login",
  "GaBreeze portal",
  "GaBreeze benefits login",
  "GaBreeze enrollment",
  "GaBreeze open enrollment",
  "GaBreeze annual enrollment",
  "GaBreeze health insurance",
  "GaBreeze medical benefits",
  "GaBreeze HSA",
  "GaBreeze FSA",
  "GaBreeze sign in",
  "GaBreeze benefits account login",
  "GaBreeze account login",
  "Georgia GaBreeze",
  "Georgia employee benefits login",
  "Georgia benefits enrollment portal",
  "State of Georgia employee benefits",
  "State of Georgia employee benefits login",
  "State of Georgia benefits login",
  "Georgia state employee benefits",
  "Georgia government employee benefits login",
  "benefits account login",
  "employee benefits portal",
  "employee benefits login",
  "open enrollment login",
  "health benefits login",
  "Georgia employee benefits enrollment",
  "State of Georgia employee portal",
  "Team Georgia benefits",
  "Georgia benefits open enrollment",
  DEFAULT_TITLE,
  SITE_DISPLAY_NAME,
  CANONICAL_HOST,
  "gabreeze.ga.gov",
  "gabreeze.ga.gov login",
  "www.gabreeze.ga.gov",
  "benefitslogin.wexhealth.com",
  "benefitslogin.wexhealth.com login",
  ...USER_SUPPLIED_KEYWORDS,
  ...DESTINATION_KEYWORDS,
  ...seoKeywords,
])

/** Alias used by CrawlerSeoPage / shared SEO body copy. */
export const SITE_KEYWORDS = SITE_SEO_KEYWORDS
